services:
  - type: web
    name: srimca-ai-backend
    runtime: python
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r backend/requirements.txt && python -m pip install -r backend/srimca/requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: mongodb+srv://n8n:n8nconnection@cluster0.guplsjx.mongodb.net # Set this in Render dashboard
      - key: MONGODB_DB_NAME
        value: srimca_ai
      - key: SMTP_USER
        value: 2025mca006@gmail.com
      - key: SMTP_PASS
        value: ocgqypybbfuudsiz
      - key: SMTP_FROM
        value: 2025mca006@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
