// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for your app.
///
/// This file contains the Firebase configuration for your app based on
/// the firebase.json configuration and the Firebase Console.
///
/// You can customize this file with your own Firebase configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC636bda4f583b3f276352f',
    appId: '1:815096047486:web:c636bda4f583b3f276352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    authDomain: 'srimcaai.firebaseapp.com',
    storageBucket: 'srimcaai.appspot.com',
    databaseURL: 'https://srimcaai-default-rtdb.firebaseio.com',
  );

  // Firebase configuration for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC636bda4f583b3f276352f',
    appId: '1:815096047486:android:408cfde9c5f2d36a76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
    databaseURL: 'https://srimcaai-default-rtdb.firebaseio.com',
  );

  // Firebase configuration for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC636bda4f583b3f276352f',
    appId: '1:815096047486:ios:d5d4866027d009db76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
    iosBundleId: 'com.example.srimcaAi',
    databaseURL: 'https://srimcaai-default-rtdb.firebaseio.com',
  );

  // Firebase configuration for macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC636bda4f583b3f276352f',
    appId: '1:815096047486:ios:d5d4866027d009db76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
    iosBundleId: 'com.example.srimcaAi',
    databaseURL: 'https://srimcaai-default-rtdb.firebaseio.com',
  );
}

