// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zJ4F2q1vP3dK1E1Y-Xq0Yc3x3H1I5yW',
    appId: '1:815096047486:web:c636bda4f583b3f276352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    authDomain: 'srimcaai.firebaseapp.com',
    storageBucket: 'srimcaai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zJ4F2q1vP3dK1E1Y-Xq0Yc3x3H1I5yW',
    appId: '1:815096047486:android:408cfde9c5f2d36a76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1zJ4F2q1vP3dK1E1Y-Xq0Yc3x3H1I5yW',
    appId: '1:815096047486:ios:d5d4866027d009db76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
    iosBundleId: 'com.example.srimcaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1zJ4F2q1vP3dK1E1Y-Xq0Yc3x3H1I5yW',
    appId: '1:815096047486:ios:d5d4866027d009db76352f',
    messagingSenderId: '815096047486',
    projectId: 'srimcaai',
    storageBucket: 'srimcaai.appspot.com',
    iosBundleId: 'com.example.srimcaAi',
  );
}
